package id.asrul.pendaki.ui.nav

object Rute {
    const val IZIN = "izin"
    const val MULAI = "mulai"
    const val PILIH_GUNUNG = "pilihGunung"
    const val PILIH_JALUR = "pilihJalur/{gunungId}"
    fun pilihJalur(gunungId: String) = "pilihJalur/$gunungId"
    const val UTAMA = "utama"
    const val MENU = "menu"
    const val POS = "pos"
    const val NAMA_POS = "namaPos"
    const val TAWARAN_POS = "tawaranPos"
    const val NAVIGASI = "navigasi"
    const val KONDISI = "kondisi"
    const val UKUR_SPO2 = "ukurSpo2"
    const val STRES = "stres"
    const val PERINGATAN_HR = "peringatanHr"
    const val PERINGATAN_AMS = "peringatanAms"
    const val PUNCAK = "puncak"
    const val KONFIRMASI_SELESAI = "konfirmasiSelesai"
    const val SELESAI = "selesai"
    const val PENGATURAN = "pengaturan"
    const val BATAS_DETAK = "batasDetak"
    const val USIA = "usia"
    const val AMBANG_SPO2 = "ambangSpo2"
    const val MINUM = "minum"
    const val DEBUG = "debug"
}
